# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),  # Changed from JSONField to CharField
                ('language', models.CharField(max_length=100)),
                ('mpaa_rating_type', models.CharField(max_length=10)),
                ('mpaa_rating_label', models.CharField(max_length=100)),
                ('user_rating', models.FloatField()),  # Changed from CharField to FloatField
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
